# Generated by Django 2.2 on 2022-06-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0003_auto_20220605_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='liked_posts', to='forum_app.User'),
        ),
    ]
